### ISSUE TITLE
Running locally but it said problem connecting to backend

### ISSUE THREAD

**Issue by wah0310** [crhuber/golinks-python#2]
I was trying out this version and was running it locally. After running all the run commands, the UI came up just fine, and it's beautiful looking.  It took my URL however, when I click on Directory, it had a bar saying "Something went bad on connecting to the backend".  Any ideas?

**Comment by crhuber** [comment]
@wah0310 i just clone the repo and followed the instructions exactly and it worked for me. I think the problem is that you need to keep the backend running so youll need to do 
`make run` keep that open and running but in a different terminal window do `make run-frontend`

**Comment by wah0310** [comment]
@crhuber Tried that, no luck. What platform are you running this on? I am running it on RHEL8.  I check the browser devtool and got this

<img width="548" alt="Screen Shot 2020-02-27 at 5 04 01 PM" src="https://user-images.githubusercontent.com/13909888/75500912-2e43bb00-5983-11ea-93ae-662e74836a5e.png">

**Comment by crhuber** [comment]
I’m on macOS
